lower_level_controller:
  ros__parameters:
    controller_type: 3  # ODrive mode (no PLC needed for testing)
    robot:
      wheel_seperation: 0.90
      wheel_radius: 0.101
      TPR: 16384
    linear_vel_limit: 1.0
    angular_vel_limit: 1.0
    linear_acc_limit: 100.2
    linear_decc_limit: 100.2
    gearRatio: 9
    odom_frame: odom_frame
    base_frame: base_footprint
    cmd_topic: cmd_vel
    debug_cmd_topic: debug/cmd_vel
    odom_topic: odom_
    emergency_stop_topic: e_stop
    barcode_topic: barcode/global
    publish_tf: false
