# Twist Mux Configuration for Zeus Robot
# This configuration multiplexes different velocity command sources

# List of topics to multiplex
topics:
  - name    : "cmd_vel"
    topic   : "/cmd_vel"
    timeout : 0.5
    priority: 10
    type    : "geometry_msgs/msg/Twist"

  - name    : "emergency_cmd_vel"
    topic   : "/emergency_cmd_vel"
    timeout : 0.5
    priority: 100
    type    : "geometry_msgs/msg/Twist"

  - name    : "joy_cmd_vel"
    topic   : "/joy/cmd_vel"
    timeout : 0.5
    priority: 5
    type    : "geometry_msgs/msg/Twist"

# Output topic
cmd_out: "/cmd_vel_out"

# Lock topics (emergency stops)
locks:
  - name    : "e_stop"
    topic   : "/e_stop"
    timeout : 0.5
    type    : "std_msgs/msg/Bool"